import { createResourceClient } from '@/api/resource'
import { api, unwrap, type ApiSuccess } from '@/lib/axios'
import type {
  Baggage,
  Branch,
  CompanyPermission,
  Car,
  CarControl,
  CarControlGroup,
  CarInsurance,
  CarInsuranceGroup,
  CompanyAccount,
  Driver,
  DriverAssignment,
  Location,
  ProductType,
  Role,
  RoleDetail,
  RoutePrice,
  Ticket,
  TripSalesDetail,
  TripSalesRow,
  TravelRoute,
  Trip,
  TripDetail,
  TripPoint,
} from '@/types/entities'

/**
 * One client per resource in the OpenAPI spec (docs/).
 * Paths match the API exactly - no renaming or aliasing.
 */

export const locationsApi = createResourceClient<Location>('locations')
export const routesApi = createResourceClient<TravelRoute>('routes')
export const routePricesApi = createResourceClient<RoutePrice>('route-prices')
export const tripsApi = createResourceClient<Trip>('trips')

/**
 * The same /trips path, typed for the GET-by-id shape.
 *
 * GET /trips/{id} returns much more than a list row (company, route prices
 * and segments, the vehicle's seats/baggage/insurance) but strips ids from
 * the nested records - see TripDetail. Two clients keep both shapes honest
 * rather than making every field optional on one type.
 */
export const tripDetailApi = createResourceClient<TripDetail>('trips')
/**
 * Trip points -> /api/v1/trip-points.
 *
 * Replaces the removed /trip-stops (now 404). Points are GENERATED by the
 * API when a trip is created - there is no POST or DELETE (both 404) - and
 * PATCH accepts only `status`, `actualArrivalAt` and `actualDepartureAt`.
 * The permission is `trip_points.*`, granting read and update only.
 *
 * There is no standalone trip-points page: points are only meaningful in the
 * context of their trip, and /trip-points has no `?tripId=` filter to scope
 * them by one. They are read from the trips response (which embeds them) and
 * edited in place - see TripDetailPage.
 */
export const tripPointsApi = createResourceClient<TripPoint>('trip-points')
export const ticketsApi = createResourceClient<Ticket>('tickets')

/**
 * Ticket sales grouped by trip -> /api/v1/tickets/trips.
 *
 * One row per trip with a `summary` (tickets sold, seats, revenue, and a
 * breakdown by status), rather than a flat list of every ticket. Unlike
 * /trips, `?startDate=`/`?endDate=` here filter by DEPARTURE, which is the
 * question a sales report is actually asked.
 */
export const tripSalesApi = createResourceClient<TripSalesRow>('tickets/trips')

/** The same path by id, which adds the trip's stops and every ticket sold. */
export const tripSalesDetailApi = createResourceClient<TripSalesDetail>('tickets/trips')
export const companyAccountsApi = createResourceClient<CompanyAccount>('company-accounts')
export const branchesApi = createResourceClient<Branch>('branches')
export const productTypesApi = createResourceClient<ProductType>('product-types')
export const carsApi = createResourceClient<Car>('cars')

/**
 * Seats -> /api/v1/seats.
 *
 * Typed as Car, not Seat, because the endpoint returns CARS with their seats
 * embedded rather than a flat seat list - the same shape as /cars, except
 * /cars truncates each `seats` array at 20 while /seats does not.
 *
 * It also paginates by SEAT: a 28-seat car appears on page 1 (seats 1-20) and
 * again on page 2 (seats 21-28), and `meta.total` counts seats. Request
 * `limit=100` to get each car once with all of its seats.
 *
 * PATCH /api/v1/seats/{id} still addresses a single seat, so `update` works
 * on a seat id even though `list` returns cars.
 */
export const seatsApi = createResourceClient<Car>('seats')
/**
 * Baggage -> /api/v1/baggage.
 *
 * GET returns FLAT rows - one per compartment, each with a carId - unlike
 * /seats, which groups them under their car.
 *
 * POST is the odd one out: it takes a discriminated body (SOME_WEIGHT with a
 * single maxWeight, or DIFFERENT_WEIGHT with a weights array) and the API
 * expands it into these rows, capped by the car's totalWeightSlots.
 */
export const baggageApi = createResourceClient<Baggage>('baggage')
/**
 * Car insurance -> /api/v1/car-insurance.
 *
 * Typed as CarInsuranceGroup, not CarInsurance, because LIST returns policies
 * GROUPED BY CAR - `[{ CarInsurance: [...] }]` - and `meta.total` counts cars
 * rather than policies. The grouped rows also omit `carId`.
 *
 * GET by id is the only read that returns a whole policy including `carId`,
 * and PATCH requires `carId` on every call, so CarInsurancePage resolves the
 * car itself instead of trusting the list row. See that page for the rest.
 */
export const carInsuranceApi = createResourceClient<CarInsuranceGroup>('car-insurance')

/** Single-policy reads/writes, where the row really is a CarInsurance. */
export const carInsuranceItemApi = createResourceClient<CarInsurance>('car-insurance')
/**
 * Car controls -> /api/v1/car-controls.
 *
 * Typed as CarControlGroup because LIST returns inspections GROUPED BY CAR:
 * `[{ id, plateNumber, controls: [...] }]`, including cars with no
 * inspections at all. Unlike car insurance, `meta.total` counts INSPECTIONS
 * and paging works, so the page can page server-side.
 */
export const carControlsApi = createResourceClient<CarControlGroup>('car-controls')

/** Single-inspection reads/writes, where the row really is a CarControl. */
export const carControlItemApi = createResourceClient<CarControl>('car-controls')
export const driversApi = createResourceClient<Driver>('drivers')
export const driverAssignmentsApi = createResourceClient<DriverAssignment>('driver-assignments')

/* ----------------------------- Roles ------------------------------ */

/**
 * Roles -> /api/v1/roles.
 *
 * The list returns each role's permissions as flat strings; GET-by-id
 * returns them as nested join rows (see RoleDetail). Creating a role with a
 * `permissions` key silently ignores it - use replaceRolePermissions.
 */
export const rolesApi = createResourceClient<Role>('roles')

/** The same path, typed for the GET-by-id shape. */
export const roleDetailApi = createResourceClient<RoleDetail>('roles')

/** Permissions the company can grant -> /api/v1/permissions. */
export const permissionsApi = createResourceClient<CompanyPermission>('permissions')

/**
 * Replace a role's permissions wholesale.
 *
 * PUT, not POST or PATCH - both 404 on this path. The array REPLACES what
 * the role had; an empty array clears everything. Values are validated
 * against the catalog, so an unknown string fails the whole request.
 */
export async function replaceRolePermissions(
  roleId: string,
  permissions: string[],
): Promise<Role> {
  return unwrap(
    api.put<ApiSuccess<Role>>(`/api/v1/roles/${roleId}/permissions`, { permissions }),
  )
}

/**
 * Every permission string the API will accept.
 *
 * Deliberately NOT /api/v1/permissions: that returns only the 82 rows the
 * company has, while the catalog has 85 - it alone carries `my_trips.read`,
 * `my_trips.update` and `reports.read`. Since PUT validates against the
 * catalog, the picker must offer the catalog.
 */
export async function fetchPermissionCatalog(): Promise<string[]> {
  const { data } = await api.get<ApiSuccess<string[]>>('/api/v1/permissions/catalog')
  return Array.isArray(data.data) ? data.data : []
}
